name: Build and test

on: [push, pull_request]

permissions:
  contents: read

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}

jobs:
  lts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          check-latest: true
      # Даем права на выполнение для gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v4
      - name: Test with Gradle
        run: ./gradlew test
        timeout-minutes: 60

  additional:
    #if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [12, 13, 14, 15, 16, 18, 19, 20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          check-latest: true
      - uses: gradle/actions/setup-gradle@v4
      - name: Test with Gradle
        run: ./gradlew test
        timeout-minutes: 60
  ea:
    #if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # The jdk links of "install-jdk.sh" are sometimes outdated, so we have to download openjdk releases from https://jdk.java.net/ by ourselves.
        jdk:
          - "https://download.java.net/java/early_access/jdk23/25/GPL/openjdk-23-ea+25_linux-x64_bin.tar.gz"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download JDK ${{ matrix.jdk }}
        run: wget -c ${{ matrix.jdk }} -O /tmp/openjdk.tar.gz
      - name: Set up JDK ${{ matrix.jdk }}
        run: mkdir -p /home/runner/openjdk && tar -xvf /tmp/openjdk.tar.gz -C /home/runner/openjdk && chmod -R 755 /home/runner/openjdk && mv /home/runner/openjdk/jdk*/* /home/runner/openjdk/
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          check-latest: true
      - uses: gradle/actions/setup-gradle@v4
      - name: Test with Gradle
        run: ./gradlew test -Ptarget.java.home=/home/runner/openjdk
        timeout-minutes: 60